#!/bin/zsh

backlight=/sys/class/backlight/intel_backlight/brightness

if [ -n "$1" ] ; then
	br=$((`cat $backlight` $1))
	sudo sh -c "echo $br > $backlight"
fi

max=/sys/class/backlight/intel_backlight/max_brightness
echo Brightness: $(cat $backlight) / $(cat $max)
