#!/bin/zsh

dev="Mouse"
if [ -n "$2" ] ; then
	dev=$1
	shift
fi

line=`xinput list | grep -n $dev | head -1 | cut -d : -f 1`

if [ -n "$line" ] ; then
	id=`xinput list --id-only | sed -n ${line}p`
	prop=338 # Accek speed

	xinput set-prop $id $prop $1
fi
