#!/bin/zsh

dev="Mouse"
if [ -n "$2" ] ; then
	dev=$1
	shift
fi

# I like sed
id=`xinput list | sed -e '/Gaming Mouse/ !d' -e 's/.*id=\([0-9]*\).*/\1/' | head -1`

if [ -n "$id" ] ; then
	# I really do
	prop=`xinput list-props $id | sed -e '/Accel Speed/ !d' -e 's/.*(\(.*\)).*/\1/' | head -1`

	xinput set-prop $id $prop $1
fi
