#!/bin/zsh

# how to register for windows:
# open regedit.exe
# goto Computer\HKEY_CLASSES_ROOT\*\shell
# right click "shell", new key "Open With Neovim"
# add new string value named "icon" value "D:\ONEDRIVE\Images\Logos\nvim.ico"
# right click "Open With Neovim", new key "command"
# add new string value: wt -w 0 wsl.exe ~/dotfiles/scripts/open_with_nvim "'"%1"'"

source ~/.extrc
file=$(wslpath "$1")
cd "$(dirname "$file")"
CONTEXT_MENU="1" vim "$file"
